In [3]:
import pandas as pd
import nltk
import re
df = pd.read_csv("raw.csv")
df.head(49)

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,5.703060e+17,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,24-02-2015 11:35,NaN,Eastern Time (US & Canada)
1,5.703010e+17,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,24-02-2015 11:15,NaN,Pacific Time (US & Canada)
2,5.703010e+17,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,24-02-2015 11:15,Lets Play,Central Time (US & Canada)
3,5.703010e+17,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,24-02-2015 11:15,NaN,Pacific Time (US & Canada)
4,5.703010e+17,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,24-02-2015 11:14,NaN,Pacific Time (US & Canada)
5,5.703010e+17,negative,1.0000,Can't Tell,NaN,Virgin America,NaN,jnardino,NaN,0,NaN,seriously would pay $30 a flight for seats th...,24-02-2015 11:14,NaN,Pacific Time (US & Canada)
6,5.703010e+17,positive,0.6745,NaN,0.0000,Virgin America,NaN,cjmcginnis,NaN,0,"@VirginAmerica yes, nearly every time I fly VX...",NaN,24-02-2015 11:13,San Francisco CA,Pacific Time (US & Canada)
7,5.703000e+17,neutral,0.6340,NaN,NaN,Virgin America,NaN,pilot,NaN,0,@VirginAmerica Really missed a prime opportuni...,NaN,24-02-2015 11:12,Los Angeles,Pacific Time (US & Canada)
8,5.703000e+17,positive,0.6559,NaN,NaN,Virgin America,NaN,dhepburn,NaN,0,"@virginamerica Well, I didn't…but NOW I DO! :-D",NaN,24-02-2015 11:11,San Diego,Pacific Time (US & Canada)
9,5.702950e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,YupitsTate,NaN,0,"@VirginAmerica it was amazing, and arrived an ...",NaN,24-02-2015 10:53,Los Angeles,Eastern Time (US & Canada)
10,5.702940e+17,neutral,0.6769,NaN,0.0000,Virgin America,NaN,idk_but_youtube,NaN,0,@VirginAmerica did you know that suicide is th...,NaN,24-02-2015 10:48,1/1 loner squad,Eastern Time (US & Canada)
11,5.702900e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,HyperCamiLax,NaN,0,@VirginAmerica I &lt;3 pretty graphics. so muc...,NaN,24-02-2015 10:30,NYC,America/New_York
12,5.702900e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,HyperCamiLax,NaN,0,@VirginAmerica This is such a great deal! Alre...,NaN,24-02-2015 10:30,NYC,America/New_York
13,5.702870e+17,positive,0.6451,NaN,NaN,Virgin America,NaN,mollanderson,NaN,0,@VirginAmerica @virginmedia I'm flying your #f...,NaN,24-02-2015 10:21,NaN,Eastern Time (US & Canada)
14,5.702860e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,sjespers,NaN,0,@VirginAmerica Thanks!,NaN,24-02-2015 10:15,"San Francisco, CA",Pacific Time (US & Canada)
15,5.702820e+17,negative,0.6842,Late Flight,0.3684,Virgin America,NaN,smartwatermelon,NaN,0,@VirginAmerica SFO-PDX schedule is still MIA.,NaN,24-02-2015 10:01,"palo alto, ca",Pacific Time (US & Canada)
16,5.702780e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,ItzBrianHunty,NaN,0,@VirginAmerica So excited for my first cross c...,NaN,24-02-2015 09:42,west covina,Pacific Time (US & Canada)
17,5.702770e+17,negative,1.0000,Bad Flight,1.0000,Virgin America,NaN,heatherovieda,NaN,0,@VirginAmerica I flew from NYC to SFO last we...,NaN,24-02-2015 09:39,this place called NYC,Eastern Time (US & Canada)
18,5.702710e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,thebrandiray,NaN,0,I ❤️ flying @VirginAmerica. ☺️👍,NaN,24-02-2015 09:15,Somewhere celebrating life.,Atlantic Time (Canada)
19,5.702680e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,JNLpierce,NaN,0,@VirginAmerica you know what would be amazingl...,NaN,24-02-2015 09:04,Boston | Waltham,Quito
20,5.702660e+17,negative,0.6705,Can't Tell,0.3614,Virgin America,NaN,MISSGJ,NaN,0,@VirginAmerica why are your first fares in May...,NaN,24-02-2015 08:55,NaN,NaN
21,5.702640e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,DT_Les,NaN,0,@VirginAmerica I love this graphic. http://t.c...,"[40.74804263, -73.99295302]",24-02-2015 08:49,NaN,NaN
22,5.702590e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,ElvinaBeck,NaN,0,@VirginAmerica I love the hipster innovation. ...,NaN,24-02-2015 08:30,Los Angeles,Pacific Time (US & Canada)
23,5.702590e+17,neutral,1.0000,NaN,NaN,Virgin America,NaN,rjlynch21086,NaN,0,@VirginAmerica will you be making BOS&gt;LAS n...,NaN,24-02-2015 08:27,"Boston, MA",Eastern Time (US & Canada)
24,5.702570e+17,negative,1.0000,Customer Service Issue,0.3557,Virgin America,NaN,ayeevickiee,NaN,0,@VirginAmerica you guys messed up my seating.....,NaN,24-02-2015 08:18,714,Mountain Time (US & Canada)
25,5.702490e+17,negative,1.0000,Customer Service Issue,1.0000,Virgin America,NaN,Leora13,NaN,0,@VirginAmerica status match program. I applie...,NaN,24-02-2015 07:49,NaN,NaN
26,5.702400e+17,negative,1.0000,Can't Tell,0.6614,Virgin America,NaN,meredithjlynn,NaN,0,@VirginAmerica What happened 2 ur vegan food o...,NaN,24-02-2015 07:11,NaN,NaN
27,5.702180e+17,neutral,0.6854,NaN,NaN,Virgin America,NaN,AdamSinger,NaN,0,@VirginAmerica do you miss me? Don't worry we'...,NaN,24-02-2015 05:44,"San Francisco, CA",Central Time (US & Canada)
28,5.702080e+17,negative,1.0000,Bad Flight,1.0000,Virgin America,NaN,blackjackpro911,NaN,0,@VirginAmerica amazing to me that we can't get...,"[42.361016, -71.02000488]",24-02-2015 05:05,"San Mateo, CA & Las Vegas, NV",NaN
29,5.701250e+17,neutral,0.6150,NaN,0.0000,Virgin America,NaN,TenantsUpstairs,NaN,0,@VirginAmerica LAX to EWR - Middle seat on a r...,"[33.94540417, -118.4062472]",23-02-2015 23:34,Brooklyn,Atlantic Time (Canada)
30,5.701140e+17,negative,1.0000,Flight Booking Problems,1.0000,Virgin America,NaN,jordanpichler,NaN,0,@VirginAmerica hi! I just bked a cool birthday...,NaN,23-02-2015 22:52,NaN,Vienna
31,5.700950e+17,neutral,1.0000,NaN,NaN,Virgin America,NaN,JCervantezzz,NaN,0,@VirginAmerica Are the hours of operation for ...,NaN,23-02-2015 21:35,"California, San Francisco",Pacific Time (US & Canada)
32,NaN,negative,1.0000,Customer Service Issue,1.0000,Virgin America,NaN,Cuschoolie1,NaN,0,"@VirginAmerica help, left expensive headphones...","[33.94209449, -118.40410103]",23-02-2015 21:10,Washington DC,Quito
33,5.700850e+17,negative,1.0000,Customer Service Issue,1.0000,Virgin America,NaN,amanduhmccarty,NaN,0,"@VirginAmerica awaiting my return phone call, ...",NaN,23-02-2015 20:55,NaN,Pacific Time (US & Canada)
34,5.700770e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,NorthTxHomeTeam,NaN,0,@VirginAmerica this is great news! America co...,"[33.2145038, -96.9321504]",23-02-2015 20:24,Texas,Central Time (US & Canada)
35,5.700520e+17,neutral,0.6207,NaN,NaN,Virgin America,NaN,miaerolinea,NaN,0,Nice RT @VirginAmerica: Vibe with the moodligh...,NaN,23-02-2015 18:46,Worldwide,Caracas
36,5.700510e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,Nicsplace,NaN,0,@VirginAmerica Moodlighting is the only way to...,NaN,23-02-2015 18:43,Central Texas,NaN
37,5.700450e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,Nicsplace,NaN,0,@VirginAmerica @freddieawards Done and done! B...,NaN,23-02-2015 18:19,Central Texas,NaN
38,5.700390e+17,neutral,0.6791,NaN,0.0000,Virgin America,NaN,elisha_malulani,NaN,0,@VirginAmerica when can I book my flight to Ha...,NaN,23-02-2015 17:54,i'm creating a monster,Pacific Time (US & Canada)
39,5.700360e+17,negative,1.0000,Customer Service Issue,1.0000,Virgin America,NaN,DannyDouglass,NaN,0,@VirginAmerica Your chat support is not workin...,NaN,23-02-2015 17:41,"San Francisco, CA",Pacific Time (US & Canada)
40,5.700340e+17,positive,0.6639,NaN,NaN,Virgin America,NaN,jamesferrandini,NaN,0,"@VirginAmerica View of downtown Los Angeles, t...",NaN,23-02-2015 17:32,NaN,NaN
41,5.700250e+17,negative,0.6688,Flight Booking Problems,0.6688,Virgin America,NaN,will_lenzenjr,NaN,0,"@VirginAmerica Hey, first time flyer next week...",NaN,23-02-2015 17:00,Iowa City,Central Time (US & Canada)
42,5.700160e+17,neutral,1.0000,NaN,NaN,Virgin America,NaN,GottAmanda,NaN,0,@VirginAmerica plz help me win my bid upgrade ...,"[34.0219817, -118.38591198]",23-02-2015 16:24,Los Angeles,NaN
43,5.700150e+17,neutral,0.6578,NaN,0.0000,Virgin America,NaN,KGervaise,NaN,0,@VirginAmerica I have an unused ticket but mov...,NaN,23-02-2015 16:20,Georgia,Pacific Time (US & Canada)
44,5.700140e+17,neutral,1.0000,NaN,NaN,Virgin America,NaN,papamurat,NaN,0,@VirginAmerica are flights leaving Dallas for ...,NaN,23-02-2015 16:13,NaN,NaN
45,5.700120e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,arieldaie,NaN,0,@VirginAmerica I'm #elevategold for a good rea...,NaN,23-02-2015 16:08,Los Angeles,NaN
46,5.700110e+17,neutral,0.6799,NaN,NaN,Virgin America,NaN,vacations7,NaN,0,@VirginAmerica DREAM http://t.co/oA2dRfAoQ2 h...,NaN,23-02-2015 16:04,Turks and caicos,NaN
47,5.700110e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,ChelseaPoe666,NaN,0,@VirginAmerica wow this just blew my mind,NaN,23-02-2015 16:01,Oakland via Midwest,Atlantic Time (Canada)
48,5.700110e+17,neutral,1.0000,NaN,NaN,Virgin America,NaN,BobGlavinVO,NaN,0,@VirginAmerica @ladygaga @carrieunderwood Afte...,NaN,23-02-2015 16:01,"New York, NY",Eastern Time (US & Canada)

In [4]:
df = df[['text']]
df.head(49)

                                                 text
0                 @VirginAmerica What @dhepburn said.
1   @VirginAmerica plus you've added commercials t...
2   @VirginAmerica I didn't today... Must mean I n...
3   @VirginAmerica it's really aggressive to blast...
4   @VirginAmerica and it's a really big bad thing...
5                                                 NaN
6   @VirginAmerica yes, nearly every time I fly VX...
7   @VirginAmerica Really missed a prime opportuni...
8     @virginamerica Well, I didn't…but NOW I DO! :-D
9   @VirginAmerica it was amazing, and arrived an ...
10  @VirginAmerica did you know that suicide is th...
11  @VirginAmerica I &lt;3 pretty graphics. so muc...
12  @VirginAmerica This is such a great deal! Alre...
13  @VirginAmerica @virginmedia I'm flying your #f...
14                             @VirginAmerica Thanks!
15      @VirginAmerica SFO-PDX schedule is still MIA.
16  @VirginAmerica So excited for my first cross c...
17  @VirginAmerica  I flew from NYC to SFO last we...
18                    I ❤️ flying @VirginAmerica. ☺️👍
19  @VirginAmerica you know what would be amazingl...
20  @VirginAmerica why are your first fares in May...
21  @VirginAmerica I love this graphic. http://t.c...
22  @VirginAmerica I love the hipster innovation. ...
23  @VirginAmerica will you be making BOS&gt;LAS n...
24  @VirginAmerica you guys messed up my seating.....
25  @VirginAmerica status match program.  I applie...
26  @VirginAmerica What happened 2 ur vegan food o...
27  @VirginAmerica do you miss me? Don't worry we'...
28  @VirginAmerica amazing to me that we can't get...
29  @VirginAmerica LAX to EWR - Middle seat on a r...
30  @VirginAmerica hi! I just bked a cool birthday...
31  @VirginAmerica Are the hours of operation for ...
32  @VirginAmerica help, left expensive headphones...
33  @VirginAmerica awaiting my return phone call, ...
34  @VirginAmerica this is great news!  America co...
35  Nice RT @VirginAmerica: Vibe with the moodligh...
36  @VirginAmerica Moodlighting is the only way to...
37  @VirginAmerica @freddieawards Done and done! B...
38  @VirginAmerica when can I book my flight to Ha...
39  @VirginAmerica Your chat support is not workin...
40  @VirginAmerica View of downtown Los Angeles, t...
41  @VirginAmerica Hey, first time flyer next week...
42  @VirginAmerica plz help me win my bid upgrade ...
43  @VirginAmerica I have an unused ticket but mov...
44  @VirginAmerica are flights leaving Dallas for ...
45  @VirginAmerica I'm #elevategold for a good rea...
46  @VirginAmerica  DREAM http://t.co/oA2dRfAoQ2 h...
47          @VirginAmerica wow this just blew my mind
48  @VirginAmerica @ladygaga @carrieunderwood Afte...

In [5]:
print(df.shape)
print(df.isnull().sum())

(49, 1)
text    1
dtype: int64

In [15]:
df["text"] = df["text"].str.lower()
df.head(49)

                                                 text
0                    virginamerica what dhepburn said
1   virginamerica plus youve added commercials exp...
2   virginamerica i didnt today must mean i need t...
3   virginamerica really aggressive blast obnoxiou...
4                  virginamerica really big bad thing
5                                                 nan
6   virginamerica yes nearly every time i fly vx e...
7   virginamerica really missed prime opportunity ...
8            virginamerica well i didntbut now i do d
9   virginamerica amazing arrived hour early youre...
10  virginamerica know suicide second leading caus...
11  virginamerica i lt pretty graphics much better...
12  virginamerica this great deal already thinking...
13  virginamerica virginmedia im flying fabulous s...
14                               virginamerica thanks
15            virginamerica sfopdx schedule still mia
16  virginamerica so excited first cross country f...
17  virginamerica i flew nyc sfo last week couldnt...
18                             i flying virginamerica
19  virginamerica know would amazingly awesome bos...
20  virginamerica first fares may three times carr...
21                       virginamerica i love graphic
22  virginamerica i love hipster innovation you fe...
23  virginamerica making bosgtlas non stop permane...
24  virginamerica guys messed seating i reserved s...
25  virginamerica status match program i applied t...
26  virginamerica what happened ur vegan food opti...
27   virginamerica miss dont worry well together soon
28  virginamerica amazing cant get cold air vents ...
29  virginamerica lax ewr middle seat red eye such...
30  virginamerica hi i bked cool birthday trip can...
31  virginamerica are hours operation club sfo pos...
32  virginamerica help left expensive headphones f...
33  virginamerica awaiting return phone call would...
34  virginamerica great news america could start f...
35  nice rt virginamerica vibe moodlight takeoff t...
36  virginamerica moodlighting way fly best experi...
37  virginamerica freddieawards done done best air...
38                 virginamerica i book flight hawaii
39       virginamerica your chat support working site
40  virginamerica view downtown los angeles hollyw...
41  virginamerica hey first time flyer next week e...
42  virginamerica plz help win bid upgrade flight ...
43  virginamerica i unused ticket moved new city d...
44  virginamerica flights leaving dallas seattle t...
45      virginamerica im elevategold good reason rock
46                                virginamerica dream
47                        virginamerica wow blew mind
48  virginamerica ladygaga carrieunderwood after l...

In [16]:
df["text"] = df["text"].apply(
    lambda x: re.sub(r"http\S+|www\S+", "", str(x))
)

df.head(49)

                                                 text
0                    virginamerica what dhepburn said
1   virginamerica plus youve added commercials exp...
2   virginamerica i didnt today must mean i need t...
3   virginamerica really aggressive blast obnoxiou...
4                  virginamerica really big bad thing
5                                                 nan
6   virginamerica yes nearly every time i fly vx e...
7   virginamerica really missed prime opportunity ...
8            virginamerica well i didntbut now i do d
9   virginamerica amazing arrived hour early youre...
10  virginamerica know suicide second leading caus...
11  virginamerica i lt pretty graphics much better...
12  virginamerica this great deal already thinking...
13  virginamerica virginmedia im flying fabulous s...
14                               virginamerica thanks
15            virginamerica sfopdx schedule still mia
16  virginamerica so excited first cross country f...
17  virginamerica i flew nyc sfo last week couldnt...
18                             i flying virginamerica
19  virginamerica know would amazingly awesome bos...
20  virginamerica first fares may three times carr...
21                       virginamerica i love graphic
22  virginamerica i love hipster innovation you fe...
23  virginamerica making bosgtlas non stop permane...
24  virginamerica guys messed seating i reserved s...
25  virginamerica status match program i applied t...
26  virginamerica what happened ur vegan food opti...
27   virginamerica miss dont worry well together soon
28  virginamerica amazing cant get cold air vents ...
29  virginamerica lax ewr middle seat red eye such...
30  virginamerica hi i bked cool birthday trip can...
31  virginamerica are hours operation club sfo pos...
32  virginamerica help left expensive headphones f...
33  virginamerica awaiting return phone call would...
34  virginamerica great news america could start f...
35  nice rt virginamerica vibe moodlight takeoff t...
36  virginamerica moodlighting way fly best experi...
37  virginamerica freddieawards done done best air...
38                 virginamerica i book flight hawaii
39       virginamerica your chat support working site
40  virginamerica view downtown los angeles hollyw...
41  virginamerica hey first time flyer next week e...
42  virginamerica plz help win bid upgrade flight ...
43  virginamerica i unused ticket moved new city d...
44  virginamerica flights leaving dallas seattle t...
45      virginamerica im elevategold good reason rock
46                                virginamerica dream
47                        virginamerica wow blew mind
48  virginamerica ladygaga carrieunderwood after l...

In [17]:
df["text"] = df["text"].apply(
    lambda x: re.sub(r"http\S+|www\S+", "", str(x))
)

df.head(49)

                                                 text
0                    virginamerica what dhepburn said
1   virginamerica plus youve added commercials exp...
2   virginamerica i didnt today must mean i need t...
3   virginamerica really aggressive blast obnoxiou...
4                  virginamerica really big bad thing
5                                                 nan
6   virginamerica yes nearly every time i fly vx e...
7   virginamerica really missed prime opportunity ...
8            virginamerica well i didntbut now i do d
9   virginamerica amazing arrived hour early youre...
10  virginamerica know suicide second leading caus...
11  virginamerica i lt pretty graphics much better...
12  virginamerica this great deal already thinking...
13  virginamerica virginmedia im flying fabulous s...
14                               virginamerica thanks
15            virginamerica sfopdx schedule still mia
16  virginamerica so excited first cross country f...
17  virginamerica i flew nyc sfo last week couldnt...
18                             i flying virginamerica
19  virginamerica know would amazingly awesome bos...
20  virginamerica first fares may three times carr...
21                       virginamerica i love graphic
22  virginamerica i love hipster innovation you fe...
23  virginamerica making bosgtlas non stop permane...
24  virginamerica guys messed seating i reserved s...
25  virginamerica status match program i applied t...
26  virginamerica what happened ur vegan food opti...
27   virginamerica miss dont worry well together soon
28  virginamerica amazing cant get cold air vents ...
29  virginamerica lax ewr middle seat red eye such...
30  virginamerica hi i bked cool birthday trip can...
31  virginamerica are hours operation club sfo pos...
32  virginamerica help left expensive headphones f...
33  virginamerica awaiting return phone call would...
34  virginamerica great news america could start f...
35  nice rt virginamerica vibe moodlight takeoff t...
36  virginamerica moodlighting way fly best experi...
37  virginamerica freddieawards done done best air...
38                 virginamerica i book flight hawaii
39       virginamerica your chat support working site
40  virginamerica view downtown los angeles hollyw...
41  virginamerica hey first time flyer next week e...
42  virginamerica plz help win bid upgrade flight ...
43  virginamerica i unused ticket moved new city d...
44  virginamerica flights leaving dallas seattle t...
45      virginamerica im elevategold good reason rock
46                                virginamerica dream
47                        virginamerica wow blew mind
48  virginamerica ladygaga carrieunderwood after l...

In [18]:
df["text"] = df["text"].apply(
    lambda x: re.sub(r"\d+", "", str(x))
)

df.head(49)

                                                 text
0                    virginamerica what dhepburn said
1   virginamerica plus youve added commercials exp...
2   virginamerica i didnt today must mean i need t...
3   virginamerica really aggressive blast obnoxiou...
4                  virginamerica really big bad thing
5                                                 nan
6   virginamerica yes nearly every time i fly vx e...
7   virginamerica really missed prime opportunity ...
8            virginamerica well i didntbut now i do d
9   virginamerica amazing arrived hour early youre...
10  virginamerica know suicide second leading caus...
11  virginamerica i lt pretty graphics much better...
12  virginamerica this great deal already thinking...
13  virginamerica virginmedia im flying fabulous s...
14                               virginamerica thanks
15            virginamerica sfopdx schedule still mia
16  virginamerica so excited first cross country f...
17  virginamerica i flew nyc sfo last week couldnt...
18                             i flying virginamerica
19  virginamerica know would amazingly awesome bos...
20  virginamerica first fares may three times carr...
21                       virginamerica i love graphic
22  virginamerica i love hipster innovation you fe...
23  virginamerica making bosgtlas non stop permane...
24  virginamerica guys messed seating i reserved s...
25  virginamerica status match program i applied t...
26  virginamerica what happened ur vegan food opti...
27   virginamerica miss dont worry well together soon
28  virginamerica amazing cant get cold air vents ...
29  virginamerica lax ewr middle seat red eye such...
30  virginamerica hi i bked cool birthday trip can...
31  virginamerica are hours operation club sfo pos...
32  virginamerica help left expensive headphones f...
33  virginamerica awaiting return phone call would...
34  virginamerica great news america could start f...
35  nice rt virginamerica vibe moodlight takeoff t...
36  virginamerica moodlighting way fly best experi...
37  virginamerica freddieawards done done best air...
38                 virginamerica i book flight hawaii
39       virginamerica your chat support working site
40  virginamerica view downtown los angeles hollyw...
41  virginamerica hey first time flyer next week e...
42  virginamerica plz help win bid upgrade flight ...
43  virginamerica i unused ticket moved new city d...
44  virginamerica flights leaving dallas seattle t...
45      virginamerica im elevategold good reason rock
46                                virginamerica dream
47                        virginamerica wow blew mind
48  virginamerica ladygaga carrieunderwood after l...

In [19]:
df["text"] = df["text"].str.replace(
    r'[^\w\s]',
    '',
    regex=True
)

df.head(49)

                                                 text
0                    virginamerica what dhepburn said
1   virginamerica plus youve added commercials exp...
2   virginamerica i didnt today must mean i need t...
3   virginamerica really aggressive blast obnoxiou...
4                  virginamerica really big bad thing
5                                                 nan
6   virginamerica yes nearly every time i fly vx e...
7   virginamerica really missed prime opportunity ...
8            virginamerica well i didntbut now i do d
9   virginamerica amazing arrived hour early youre...
10  virginamerica know suicide second leading caus...
11  virginamerica i lt pretty graphics much better...
12  virginamerica this great deal already thinking...
13  virginamerica virginmedia im flying fabulous s...
14                               virginamerica thanks
15            virginamerica sfopdx schedule still mia
16  virginamerica so excited first cross country f...
17  virginamerica i flew nyc sfo last week couldnt...
18                             i flying virginamerica
19  virginamerica know would amazingly awesome bos...
20  virginamerica first fares may three times carr...
21                       virginamerica i love graphic
22  virginamerica i love hipster innovation you fe...
23  virginamerica making bosgtlas non stop permane...
24  virginamerica guys messed seating i reserved s...
25  virginamerica status match program i applied t...
26  virginamerica what happened ur vegan food opti...
27   virginamerica miss dont worry well together soon
28  virginamerica amazing cant get cold air vents ...
29  virginamerica lax ewr middle seat red eye such...
30  virginamerica hi i bked cool birthday trip can...
31  virginamerica are hours operation club sfo pos...
32  virginamerica help left expensive headphones f...
33  virginamerica awaiting return phone call would...
34  virginamerica great news america could start f...
35  nice rt virginamerica vibe moodlight takeoff t...
36  virginamerica moodlighting way fly best experi...
37  virginamerica freddieawards done done best air...
38                 virginamerica i book flight hawaii
39       virginamerica your chat support working site
40  virginamerica view downtown los angeles hollyw...
41  virginamerica hey first time flyer next week e...
42  virginamerica plz help win bid upgrade flight ...
43  virginamerica i unused ticket moved new city d...
44  virginamerica flights leaving dallas seattle t...
45      virginamerica im elevategold good reason rock
46                                virginamerica dream
47                        virginamerica wow blew mind
48  virginamerica ladygaga carrieunderwood after l...

In [20]:
df["text"] = df["text"].apply(
    lambda x: re.sub(r"[^a-zA-Z\s]", "", str(x))
)

df.head(49)

                                                 text
0                    virginamerica what dhepburn said
1   virginamerica plus youve added commercials exp...
2   virginamerica i didnt today must mean i need t...
3   virginamerica really aggressive blast obnoxiou...
4                  virginamerica really big bad thing
5                                                 nan
6   virginamerica yes nearly every time i fly vx e...
7   virginamerica really missed prime opportunity ...
8            virginamerica well i didntbut now i do d
9   virginamerica amazing arrived hour early youre...
10  virginamerica know suicide second leading caus...
11  virginamerica i lt pretty graphics much better...
12  virginamerica this great deal already thinking...
13  virginamerica virginmedia im flying fabulous s...
14                               virginamerica thanks
15            virginamerica sfopdx schedule still mia
16  virginamerica so excited first cross country f...
17  virginamerica i flew nyc sfo last week couldnt...
18                             i flying virginamerica
19  virginamerica know would amazingly awesome bos...
20  virginamerica first fares may three times carr...
21                       virginamerica i love graphic
22  virginamerica i love hipster innovation you fe...
23  virginamerica making bosgtlas non stop permane...
24  virginamerica guys messed seating i reserved s...
25  virginamerica status match program i applied t...
26  virginamerica what happened ur vegan food opti...
27   virginamerica miss dont worry well together soon
28  virginamerica amazing cant get cold air vents ...
29  virginamerica lax ewr middle seat red eye such...
30  virginamerica hi i bked cool birthday trip can...
31  virginamerica are hours operation club sfo pos...
32  virginamerica help left expensive headphones f...
33  virginamerica awaiting return phone call would...
34  virginamerica great news america could start f...
35  nice rt virginamerica vibe moodlight takeoff t...
36  virginamerica moodlighting way fly best experi...
37  virginamerica freddieawards done done best air...
38                 virginamerica i book flight hawaii
39       virginamerica your chat support working site
40  virginamerica view downtown los angeles hollyw...
41  virginamerica hey first time flyer next week e...
42  virginamerica plz help win bid upgrade flight ...
43  virginamerica i unused ticket moved new city d...
44  virginamerica flights leaving dallas seattle t...
45      virginamerica im elevategold good reason rock
46                                virginamerica dream
47                        virginamerica wow blew mind
48  virginamerica ladygaga carrieunderwood after l...

In [21]:
df["text"] = df["text"].apply(
    lambda x: re.sub(r"\s+", " ", str(x)).strip()
)

df.head(49)

                                                 text
0                    virginamerica what dhepburn said
1   virginamerica plus youve added commercials exp...
2   virginamerica i didnt today must mean i need t...
3   virginamerica really aggressive blast obnoxiou...
4                  virginamerica really big bad thing
5                                                 nan
6   virginamerica yes nearly every time i fly vx e...
7   virginamerica really missed prime opportunity ...
8            virginamerica well i didntbut now i do d
9   virginamerica amazing arrived hour early youre...
10  virginamerica know suicide second leading caus...
11  virginamerica i lt pretty graphics much better...
12  virginamerica this great deal already thinking...
13  virginamerica virginmedia im flying fabulous s...
14                               virginamerica thanks
15            virginamerica sfopdx schedule still mia
16  virginamerica so excited first cross country f...
17  virginamerica i flew nyc sfo last week couldnt...
18                             i flying virginamerica
19  virginamerica know would amazingly awesome bos...
20  virginamerica first fares may three times carr...
21                       virginamerica i love graphic
22  virginamerica i love hipster innovation you fe...
23  virginamerica making bosgtlas non stop permane...
24  virginamerica guys messed seating i reserved s...
25  virginamerica status match program i applied t...
26  virginamerica what happened ur vegan food opti...
27   virginamerica miss dont worry well together soon
28  virginamerica amazing cant get cold air vents ...
29  virginamerica lax ewr middle seat red eye such...
30  virginamerica hi i bked cool birthday trip can...
31  virginamerica are hours operation club sfo pos...
32  virginamerica help left expensive headphones f...
33  virginamerica awaiting return phone call would...
34  virginamerica great news america could start f...
35  nice rt virginamerica vibe moodlight takeoff t...
36  virginamerica moodlighting way fly best experi...
37  virginamerica freddieawards done done best air...
38                 virginamerica i book flight hawaii
39       virginamerica your chat support working site
40  virginamerica view downtown los angeles hollyw...
41  virginamerica hey first time flyer next week e...
42  virginamerica plz help win bid upgrade flight ...
43  virginamerica i unused ticket moved new city d...
44  virginamerica flights leaving dallas seattle t...
45      virginamerica im elevategold good reason rock
46                                virginamerica dream
47                        virginamerica wow blew mind
48  virginamerica ladygaga carrieunderwood after l...

In [22]:
nltk.download("stopwords")
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))
df["text"] = df["text"].apply(
    lambda x: " ".join(word for word in x.split() if word not in stop_words)
)
df.head(49)

[nltk_data] Downloading package stopwords to C:\Users\HUMAIRUL
[nltk_data]     JASHIRA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                                                 text
0                         virginamerica dhepburn said
1   virginamerica plus youve added commercials exp...
2   virginamerica didnt today must mean need take ...
3   virginamerica really aggressive blast obnoxiou...
4                  virginamerica really big bad thing
5                                                 nan
6   virginamerica yes nearly every time fly vx ear...
7   virginamerica really missed prime opportunity ...
8                         virginamerica well didntbut
9   virginamerica amazing arrived hour early youre...
10  virginamerica know suicide second leading caus...
11  virginamerica lt pretty graphics much better m...
12  virginamerica great deal already thinking nd t...
13  virginamerica virginmedia im flying fabulous s...
14                               virginamerica thanks
15            virginamerica sfopdx schedule still mia
16  virginamerica excited first cross country flig...
17  virginamerica flew nyc sfo last week couldnt f...
18                               flying virginamerica
19  virginamerica know would amazingly awesome bos...
20  virginamerica first fares may three times carr...
21                         virginamerica love graphic
22  virginamerica love hipster innovation feel goo...
23  virginamerica making bosgtlas non stop permane...
24  virginamerica guys messed seating reserved sea...
25  virginamerica status match program applied thr...
26  virginamerica happened ur vegan food options l...
27   virginamerica miss dont worry well together soon
28  virginamerica amazing cant get cold air vents ...
29  virginamerica lax ewr middle seat red eye noob...
30  virginamerica hi bked cool birthday trip cant ...
31  virginamerica hours operation club sfo posted ...
32  virginamerica help left expensive headphones f...
33  virginamerica awaiting return phone call would...
34  virginamerica great news america could start f...
35  nice rt virginamerica vibe moodlight takeoff t...
36  virginamerica moodlighting way fly best experi...
37  virginamerica freddieawards done done best air...
38                   virginamerica book flight hawaii
39            virginamerica chat support working site
40  virginamerica view downtown los angeles hollyw...
41  virginamerica hey first time flyer next week e...
42  virginamerica plz help win bid upgrade flight ...
43  virginamerica unused ticket moved new city don...
44  virginamerica flights leaving dallas seattle t...
45      virginamerica im elevategold good reason rock
46                                virginamerica dream
47                        virginamerica wow blew mind
48  virginamerica ladygaga carrieunderwood last ni...

In [23]:
df.to_csv("clean.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!